package com.effix.api.enums;

public enum EmissionFactorType {
    DIESEL, PETROL, HYBRID, CNG, LPG, PLUGIN_HYBRID_EV, BATTERY_EV, REFRIGERANTS, EQUIPMENT, WASTE, ELECTRICITY, NATURAL_GAS, EMPLOYEE_COMMUTE_AND_BUSINESS_TRAVEL, WATER_SUPPLY
}
