package com.effix.api.enums;

public enum LookupType {
    FUEL_TYPE, VEHICLE_SIZE, UNIT, GWP, REFRIGERANT_APPLIANCE, WASTE_TREATMENT, COUNTRY, ELECTRICITY_PROVIDER, NATURAL_GAS_PROVIDER,
    VEHICLE_MODEL, FLIGHT_CLASS, WATER_SUPPLY_PROVIDER
}
